version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Asia/Tokyo
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '09:00'
      timezone: Asia/Tokyo
