name: Scan secrets
on:
  pull_request:
    branches:
      - main
jobs:
  ScanSecrets:
    name: Scan secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan secrets
        uses: docker://ghcr.io/trufflesecurity/trufflehog:3.41.1
        with:
          args: git file://. --only-verified --fail --no-update --since-commit=main
